# Generated by Django 5.1.6 on 2025-05-03 09:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='cv',
        ),
        migrations.AddField(
            model_name='application',
            name='current_job',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hope_salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='VerificationDocument',
        ),
    ]
