# Generated by Django 5.1.6 on 2025-05-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parttime_job.job'),
        ),
    ]
