# Generated by Django 5.1.6 on 2025-06-01 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0002_conversation_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_date']},
        ),
        migrations.CreateModel(
            name='CommentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('employer_reply', models.TextField(blank=True)),
                ('rating_employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parttime_job.rating')),
            ],
            options={
                'abstract': False,
            },
        )
    ]
