# Generated by Django 5.1.6 on 2025-05-13 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0002_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(blank=True, help_text='Firebase user UID', max_length=255, null=True)),
                ('firebase_email', models.EmailField(blank=True, help_text='Firebase authentication email', max_length=254, null=True)),
                ('_firebase_password', models.BinaryField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
