# Generated by Django 5.1.6 on 2025-05-08 19:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0002_notification_job_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationdocument',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='verificationdocument',
            name='active',
        ),
        migrations.RemoveField(
            model_name='verificationdocument',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='verificationdocument',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='document_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document_back'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='document_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document_front'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='selfie_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='selfie_image'),
        ),
    ]
