# Generated by Django 5.1.6 on 2025-05-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_date']},
        ),
    ]
