# Generated by Django 5.1.6 on 2025-05-04 09:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0003_comment_notification_follow_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv'),
        ),
    ]
