# Generated by Django 5.1.6 on 2025-06-03 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0003_alter_conversation_options_commentdetail_userprofile'),
    ]

    operations = [
       
           
    ]
