# Generated by Django 5.1.6 on 2025-06-03 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0004_employerrating_is_reading_rating_is_reading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyCommetFromEmployerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('candidate_reply', models.TextField(blank=True)),
                ('rating_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parttime_job.employerrating')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
