# Generated by Django 5.1.6 on 2025-04-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0004_company_companyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyimage',
            old_name='employer',
            new_name='company',
        ),
    ]
