# Generated by Django 5.1.6 on 2025-04-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0005_rename_employer_companyimage_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
