# Generated by Django 5.1.6 on 2025-06-11 00:58

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0005_employerrating_is_reading_rating_is_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='from_salary',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='job',
            name='negotiable_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='to_salary',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='job',
            name='unit_salary',
            field=models.CharField(choices=[('dg', 'đồng/giờ'), ('tt', 'triệu/tháng')], default='dg', max_length=50),
        )
    ]
