# Generated by Django 5.1.6 on 2025-06-11 09:33

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0006_employerrating_is_reading_job_from_salary_and_more'),
    ]

    operations = [
      
        
    ]
