# Generated by Django 5.1.6 on 2025-06-12 13:45

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttime_job', '0007_remove_job_negotiable_salary_remove_job_salary_and_more'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='userprofile',
            name='firebase_password',
        ),
        
        migrations.AddField(
            model_name='userprofile',
            name='_firebase_password',
            field=models.BinaryField(blank=True, max_length=255, null=True),
        ),
    ]
