"""
Django settings for parttime_job_management project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import pymysql  # type: ignore
from cloudinary.utils import cloudinary_url  # type: ignore
import cloudinary.uploader  # type: ignore
import cloudinary  # type: ignore
from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mxv%^zkz*#e&olze4&4&t-_m%h+qc2+7v%iua7w4$q-n3@j&8b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.ngrok-free.app', '192.168.1.140', 'localhost', '127.0.0.1']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
                                                                                       

ONFIDO_API_TOKEN= 'api_live.O50cvuLZRQm.dotpcowwuN_7B_LHwJwd40mo29X-vFJv'
ONFIDO_WEBHOOK_SECRET='uVirHXhiwZuCyNvKX_0gMqQ6YlvOiPBL'
ONFIDO_API_URL = 'https://api.onfido.com/v3.6/applicants'
WORKFLOW_ID = 'b5e8c290-d48f-4cbc-b602-b2b52987f392'  # ID của workflow bạn đã tạo trên Onfido


ID_ANALYZER_API_KEY= '1cmi6EWuJ0cbIT6yqsFQvYbUqNFLwfpe'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parttime_job.apps.ParttimeJobConfig',
    'debug_toolbar',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'cloudinary',
    'oauth2_provider',
    'allauth.socialaccount.providers.google',
    'django_rest_passwordreset',
    'django_extensions',
    'drf_spectacular',
    'django_celery_beat',
    'django_celery_results',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',
]

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'basic': {
            'type': 'basic'
        }
    },
    'USE_SESSION_AUTH': False,
    'VALIDATOR_URL': None,
}

REDOC_SETTINGS = {
    'LAZY_RENDERING': False,
}

AUTHENTICATION_BACKENDS = [
    'parttime_job.auth_backend.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend'
]


CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'parttime_job_management.urls'

LOGIN_URL = '/login/'


# Configuration
cloudinary.config(
    cloud_name="do43r8nr0",
    api_key="947875495844325",
    # Click 'View API Keys' above to copy your API secret
    api_secret="evQEPk5TbxIMpCWbbXl8sLMbo6A",
    secure=True
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication'
        
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Tên API của bạn',
    'DESCRIPTION': 'Mô tả ngắn về API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # Tắt schema gốc nếu chỉ muốn hiển thị UI
    'COMPONENT_SPLIT_REQUEST': True,
    # Nếu dùng token-based authentication:
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
    'SECURITY': [{'Bearer': []}],
    'COMPONENT_SPLIT_REQUEST': True,
    'AUTHENTICATION_WHITELIST': ['rest_framework.authentication.TokenAuthentication'],
    'SECURITY_SCHEMES': {
        'Bearer': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        },
    },
}

pymysql.install_as_MySQLdb()

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'parttime_job.User'

WSGI_APPLICATION = 'parttime_job_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'parttimejobmanagementt',
        'USER': 'root',
        'PASSWORD': 'Think!7688',
        'HOST': '' # mặc định localhost
    }
}

CELERY_BROKER_URL = 'redis://localhost:6379/0'


CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_BROKER_REDIS_URL="redis://localhost:6380"




# DEBUG = True
DEBUG = config("DEBUG", cast=bool, default=False)
...

# add our newly installed packages to INSTALLED_APPS

# save Celery task results in Django's database
CELERY_RESULT_BACKEND = "django-db"

# This configures Redis as the datastore between Django + Celery
CELERY_BROKER_URL = config('CELERY_BROKER_REDIS_URL', default='redis://192.168.1.18:6379')
# if you out to use os.environ the config is:
# CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_REDIS_URL', 'redis://localhost:6379')


# this allows you to schedule items in the Django admin.
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 600,
    'APPLICATION_MODEL': 'oauth2_provider.Application',
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope'},
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.OAuthLibCore',
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'anhqui04062004@gmail.com'
EMAIL_HOST_PASSWORD = "vhqt qoqg vemh liqf"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'anhqui04062004@gmail.com'


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# SITE_ID = 1
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = 'email'

SITE_URL = 'http://192.168.1.140:8000'



CLIENT_ID= '8Y4PM14zeiZMnu5hrj86vyf9MrwA6Yis2iHQLq9J'
CLIENT_SECRET='6JrR2e167SJ9vOUrggq1HjTI9Pu03313LLLlVjLy1aXf8CKMpgP4gOyaPhVEsSW0vK0G8dqRxhzZ2Nf1TnsdMXAFRV3iWjDELuadf3OMkwbfEDMHpNX4tPGRYy6E9QUN'

# client_id: 'yrxHM4IVS0VYNk49UPborlwuxLby1EUH91ASxfUo'
# client_secret: 'DjJegQAdcXZjvbKz52L9FVyMxxyXv92pDr8UuOE4I3FhtIaYHQRgXnm9oJHT8xMcezvGVmFf0fE2yJaApSlchJwSD2gUbwmnA5nszfSEeOPBSlXZ7JUsbOpz473qpaoJ'

SPECTACULAR_SETTINGS = {
    'DEBUG': True,
}


ONFIDO_REGION = 'EU' 


# parttime_job_management/settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}